version: '2'
services:
    hyperf:
        build: ./docker/hyperf
        container_name: hyperf
        restart: always
        volumes:
            - .:/opt/www
        expose:
             - "9501"
             - "9502"
        privileged: true

    hyperf-reids:
        build: ./docker/redis
        container_name: hyperf-redis
        restart: always
        ports:
          - "6900:6379"

    hyperf-mysql:
        build: ./docker/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: echarts_stock
            MYSQL_USER: hyperf
            MYSQL_PASSWORD: 123456
        ports:
        - "3309:3306"
        volumes:
        - ./docker/mysql/data:/var/lib/mysql

#使用方法: docker-compose -f docker-compose.yml up -d