# Default Dockerfile
#
# @link     https://www.hyperf.io
# @document https://hyperf.wiki
# @contact  group@hyperf.io
# @license  https://github.com/hyperf/hyperf/blob/master/LICENSE

FROM mysql:latest

# EXPOSE 3609

WORKDIR /root/backup
CMD ["chmod", "+x", "/root/backup/backup.sh"]